name: AreaExecute
main: cn.innc11.areaexecute.Main
version: "1.1"
author: innc11
api: ["1.0.0"]
commands:
  blockcommand:
    description: "AreaExecute plugin"
    aliases: ["ae", "acc"]
    usage: "/bc <set/remove/list/reload> [args]"